### ISSUE TITLE
EDMC constantly crashes

### ISSUE THREAD

**Issue by BeGlorious** [Marginal/EDMarketConnector#381]
I can't keep EDMC open for more than a minute before it gets hung up, and then crashes. I've tried starting EDMC both before and during running ED, as well as several reinstalls of EDMC, and PC reboots. It always crashes quickly after launch.

[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/2725256/EDMarketConnector.log)

**Comment by ziggurats** [comment]
Not seeing the constant crashing, but whenever I click Update or File -> Status, I see "Fetching data..." at the bottom of the window and EDMC hangs. If I place the cursor over the EDMC window it shows a spinner.   Clicking on the EDMC window causes the app to crash then.  I compared my log file with the attached, and it's pretty much the same, with the only variation being in the frontierstore call.  Looks like repeated attempts at auth that aren't getting the expected JSON response.  I think, anyway.

**Comment by Atomicbeast101** [comment]
Can confirm. The program hangs up as soon as "Fetching data..." shows up.

**Comment by Just-A-Nice-Guy** [comment]
same here

**Comment by BeGlorious** [comment]
It's working fine, today. I didn't change anything, so I assume the problem was server-side.

**Comment by ziggurats** [comment]
I'm still seeing   the behaviour.  HTML in the log file looks like it the same login page that came up when I ran EDMC.

**Comment by ziggurats** [comment]
Interesting.  I got the login page again after s few attempts to update and logged in again using my steam account, and this time I got:
`Auth	Negative response "auth/?error=access_denied&state=Tp3dd6x-R5w&error_description=User+not+found"`
in the log file.  I tried again after logging out of steam in the browser; same result.  I have my steam account tied to a frontier account and tried a third time using the credentials, and I successfully logged in.  Is this a problem with steam accounts at this point now?

**Comment by BeGlorious** [comment]
Can confirm: Logging in with Steam seems to be the problem. Logging in with my Frontier account works just fine.

**Comment by Marginal** [comment]
Should be fixed in [Release 3.33](
https://github.com/Marginal/EDMarketConnector/releases/latest) - an invalid Steam login will cause an error and an opportunity to re-authenticate rather than a hang.

As far as I can tell, Steam users should always just log in using Frontier account credentials.

**Comment by RPGHoldingRaptor** [comment]
Issue is back, the past few days it worked fine till today. I'm using the newest version (3.36).

**Comment by RPGHoldingRaptor** [comment]
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/2768313/EDMarketConnector.log)
Pretty sure that this is the log.

**Comment by Marginal** [comment]
Should be working now - Frontier have fixed their API.
